#! /bin/bash
# cd /home/mschilling/Desktop/gbs15/mstr/bwa_out/

for i in *.sorted.bam; do
    #file=$(echo $i | cut -f7 -d/)
    id=$(echo $i | cut -f1 -d.)
    #id=$(echo $id | cut -f7 -d/)
    #RG=\'@RG'\t'ID:${id}\'
    echo $id
    samtools index $i 

done


